# variable file of our chart#
#----------------------------
#Wordpress variables
#------------------

wp_kind: Deployment

wp_name: wordpress
     
wp_replicas: 2

wp_pod_name: wp-pod

wp_pod_label: wp

wp_container_name: wpcont

wp_image: wordpress:5.1.1

#--------------------------#
#SQL variables
#-------------

sql_kind: StatefulSet

sql_name: database

sql_replicas: 3

sql_pod_name: databasepod

sql_pod_labels: sql

sql_container_name: dbcont

sql_image: mysql:5.7

mysql_database: wordpress

mysql_user: prabal

sql_container_port: 3306

#----------------------------#
#InternalLoadBalancer Variable
#-----------------------------

clusterip_name: clusterip

clusterip_type: ClusterIP

clusterip_port_name: database

clusterip_backend_port: 3306

#------------------
#Nodeport Variables
#------------------

nodeport_name: npwp

nodeport_target_port: 80

nodeport: 30001

#------------------
#ConfigMap Variables
#-------------------

configmap_name: mysql-cm

configmap_label: cm

#--------------------
#Secret Variables
#--------------------

secret_name: sql-secret

secret_root_password: cHJhYmFs

secret_sql_password: cHJhYmFs

#------------------------------------
#Liveness & Readiness Probe
#------------------------------------

port: 3306

initialDelaySeconds: 7

failureThreshold: 5

periodSeconds: 10
