#Making the headless service 
apiVersion: v1
kind: Service
metadata:
        name: {{ .Values.clusterip_name }}
spec:
      selector:
              name: {{ .Values.sql_pod_labels }}
      type: {{ .Values.clusterip_type }}
      clusterIP: None
      ports:
      - name: {{ .Values.clusterip_port_name }}
        port: {{ .Values.clusterip_backend_port }}
