apiVersion: apps/v1 
kind: Deployment
metadata: 
     name: "dp1"
spec:
     replicas: 3
     selector:
             matchLabels:
                     name: helm
     template:
             metadata:
                   name: "pod2"
                   labels:
                         name: helm
             spec:
                containers:
                - name: "cont2"
                  image: prabal03/sshos:v1

                     


