apiVersion: v1
kind: Service
metadata:
        name: "npwp"
spec:
     selector:
            name: {{ .Values.wp_pod_label }}
     ports:
     - targetPort: {{ .Values.nodeport_target_port }}
       port: {{ .Values.sql_container_port }}
       nodePort: {{ .Values.nodeport }}
     type: NodePort
       
