#------------Sql yaml file-----------------#
apiVersion: apps/v1
kind: {{ .Values.sql_kind }}
metadata:
        name: {{ .Values.sql_name }}
spec:
      replicas: {{ .Values.sql_replicas }}
      selector:
              matchLabels:
                      name: {{ .Values.sql_pod_labels }}
      serviceName: clusterip                
      template:
              metadata:
                      name: {{ .Values.sql_pod_name }}
                      labels:
                              name: {{ .Values.sql_pod_labels }}
              spec:
                  containers:
                  - name: {{ .Values.sql_container_name }}
                    image: {{ .Values.sql_image }}
                    env:
                    - name: "MYSQL_ROOT_PASSWORD"
                      valueFrom:
                         secretKeyRef:
                                 name: {{ .Values.secret_name }}
                                 key: root
                    - name: "MYSQL_DATABASE"
                      value: {{ .Values.mysql_database }}
                    - name: "MYSQL_USER"
                      value: {{ .Values.mysql_user }}
                    - name: "MYSQL_PASSWORD"
                      valueFrom:
                        secretKeyRef:                                      
                           name: {{ .Values.secret_name }}
                           key: sql                     
                    ports:
                    - containerPort: {{ .Values.sql_container_port }}
                      name: {{ .Values.sql_pod_name }}
                    volumeMounts:
                    - name: sql-config-map
                      mountPath: /mnt/config-map              
                  volumes:
                  - name: sql-config-map
                    configMap:
                            name: {{ .Values.configmap_name }}


