apiVersion: apps/v1
kind: {{ .Values.wp_kind }}
metadata: 
    name: {{ .Values.wp_name }}
spec:
      replicas: {{ .Values.wp_replicas }}
      selector:
              matchLabels:
                      name: {{ .Values.wp_pod_label }}
      template:
              metadata:
                      name: {{ .Values.wp_pod_name }}
                      labels:
                            name: {{ .Values.wp_pod_label }}
              spec:  
                 containers:
                 - name: {{ .Values.wp_container_name }}
                   image: {{ .Values.wp_image }}
                   env: 
                   - name: "WORDPRESS_DB_HOST"
                     value: database-0.clusterip.default.svc.cluster.local:3306
                   - name: "WORDPRESS_DB_USER"  
                     value: {{ .Values.mysql_user }}
                   - name: "WORDPRESS_DB_PASSWORD"
                     valueFrom:
                        secretKeyRef:
                                name: {{ .Values.secret_name }}
                                key: sql
                           
                   - name: "WORDPRESS_DB_NAME"
                     value: {{ .Values.mysql_database }}
                   readinessProbe:
                      exec:
                        command:
                        - curl
                        - database-0.clusterip.default.svc.cluster.local:3306
                      initialDelaySeconds: 5
                      periodSeconds: 5
                           
