apiVersion: apps/v1
kind: Deployment
metadata: 
    name: wordpress
spec:
      replicas: 2
      selector:
              matchLabels:
                      name: wp
      template:
              metadata:
                      name: "wpod"
                      labels:
                            name: wp
              spec:  
                 containers:
                 - name: "wpcont"
                   image: wordpress:5.1.1
                   env: 
                   - name: "WORDPRESS_DB_HOST"
                     value: clusterip.default.svc.cluster.local:8080
                   - name: "WORDPRESS_DB_USER"  
                     value: prabal
                   - name: "WORDPRESS_DB_PASSWORD"
                     value: prabal
                   - name: "WORDPRESS_DB_NAME"
                     value: wordpress
                           
